/*
 * PackViewer.java
 *
 * Created on 12 de noviembre de 2011, 13:40
 */

package com.asqueados.vpm.view.swing;

import com.asqueados.vpm.entities.Pack;
import com.asqueados.vpm.xml.PackXmlReader;
import com.asqueados.vpm.xml.XmlReaderException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author  Pablo J. Urbano Santos <flamma at member.fsf.org>
 */
public class PackViewer extends javax.swing.JFrame {
    private Pack pack;
    
    /** Creates new form PackViewer */
    public PackViewer() {
        initComponents();
    }
    
    public PackViewer(Pack pack) {
        this.pack = pack;
        initComponents();
    }
    
    public void setPackName(String name) {
        packPanel.setName(name);
    }
    
    public void loadPack(Pack pack) {
        packPanel.setPack(pack);
        pack();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packPanel = new com.asqueados.vpm.view.swing.PackPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().add(packPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

                PackViewer view = new PackViewer();
                view.setVisible(true);

                try {
                    PackXmlReader reader = new PackXmlReader("data/chars/packSample.xml");
                    Pack pack = reader.readPack();
                    view.loadPack(pack);
                } catch (XmlReaderException ex) {
                    view.setPackName("Error loading pack");
                    Logger.getLogger(getClass().getName()).log(Level.SEVERE, null, ex);
                }
                
                
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.asqueados.vpm.view.swing.PackPanel packPanel;
    // End of variables declaration//GEN-END:variables
    
}
