/*
 * PersonageAttributesPanel.java
 *
 * Created on 23 de octubre de 2011, 12:49
 */

package com.asqueados.vpm.view.swing;

import com.asqueados.vpm.entities.Personage;
import com.asqueados.vpm.view.text.Descriptor;
import com.asqueados.vpm.view.text.HtmlDescriptor;

/**
 *
 * @author  Pablo J. Urbano Santos <flamma at member.fsf.org>
 */
public class PersonageAttributesPanel extends javax.swing.JPanel {
    
    /** Creates new form PersonageAttributesPanel */
    public PersonageAttributesPanel() {
        super();
        initComponents();
    }

    public PersonageAttributesPanel(Personage character) {
        this();
        if(character!=null) {
            Descriptor descriptor = new HtmlDescriptor();
            String description = descriptor.getPersonageDescription(character);
            descriptionLabel.setText("<html>"+description+"</html>");
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        descriptionLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        descriptionLabel.setText("Character description."); // NOI18N
        add(descriptionLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel descriptionLabel;
    // End of variables declaration//GEN-END:variables
    
}
