/*
 * PersonageSkillsPanel.java
 *
 * Created on 30 de octubre de 2011, 12:19
 */

package com.asqueados.vpm.view.swing;

import com.asqueados.vpm.app.Application;
import com.asqueados.vpm.entities.Personage;
import com.asqueados.vpm.entities.Trait;
import com.asqueados.vpm.view.TraitTypes;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author  Pablo J. Urbano Santos <flamma at member.fsf.org>
 */
public class PersonageSkillsPanel extends javax.swing.JPanel {
    private Personage character;
    
    /** Creates new form PersonageSkillsPanel */
    public PersonageSkillsPanel() {        
        initComponents();
    }
    
    public PersonageSkillsPanel(Personage character) {
        this.character = character;
        initComponents();
        
        if(character!=null)
            loadCharacter();
        
    }
    
    private void loadCharacter() {
        List<String> skillsNames= TraitTypes.getSkillsNames();
        for(String name: skillsNames) {
            Trait trait = character.getTrait(name);
            
            if( trait != null ) {
                String traitName = Application.getTranslator().translate(name);
                String traitDescription = Application.getHtmlDescriptor().getTraitValueDescription(trait);
                
                if(traitDescription != null) {
                    JLabel nameLabel = new JLabel(traitName);
                    add(nameLabel);
                    JLabel valueLabel = new JLabel("<html>"+traitDescription+"</html>");
                    add(valueLabel);
                }
                    
            }
            
        }

    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SkillsLabel = new javax.swing.JLabel();
        emptyLabel = new javax.swing.JLabel();

        setLayout(new java.awt.GridLayout(0, 2));

        SkillsLabel.setFont(new java.awt.Font("Cantarell", 1, 15));
        SkillsLabel.setText(Application.getTranslator().translate("SKILLS")); // NOI18N
        add(SkillsLabel);
        add(emptyLabel);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SkillsLabel;
    private javax.swing.JLabel emptyLabel;
    // End of variables declaration//GEN-END:variables
    
}
