/*
 * PersonagePortraitPanel.java
 *
 * Created on 23 de octubre de 2011, 12:07
 */

package com.asqueados.vpm.view.swing;

import com.asqueados.vpm.app.Application;
import com.asqueados.vpm.entities.Personage;
import com.asqueados.vpm.entities.Trait;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author  Pablo J. Urbano Santos <flamma at member.fsf.org>
 */
public class PersonagePortraitPanel extends javax.swing.JPanel {
    
    public PersonagePortraitPanel() {
        super();
        initComponents();
    }
    
    PersonagePortraitPanel(Personage character) {
        this();
        
        boolean setted=false;
        
        if ( character == null ) 
            setDefaultPortrait(null);
        else {
            String portraitPath=null;
            String sex=null;

            Trait porTrait = character.getTrait("portrait");
            if( porTrait != null) {
                try {
                    String portraitsDir = Application.getDataConfiguration().getOption("portraitsDir");
                    portraitPath =  portraitsDir +"/"+ porTrait.getValue() +".png";
                    BufferedImage portrait = ImageIO.read(new File(portraitPath));
                    portraitLabel.setIcon(new ImageIcon(portrait));
                    setted=true;
                } catch (IOException ex) {
                    Logger.getLogger(getClass().getName()).log(Level.WARNING, "Cannot find portrait "+portraitPath);
                }
            } 
            // if not portrait is set or if portrait was not found
            if (!setted) {
                Trait sexTrait = character.getTrait("sex");
                if( sexTrait == null) {
                    setDefaultPortrait(null);
                } else {
                    sex = (String) sexTrait.getValue();
                    setDefaultPortrait(sex);
                }
            }

            
        }

    }
    /** Creates new form PersonagePortraitPanel */
    public PersonagePortraitPanel(String path, String sex) {
        this();
        
        if(path==null) {
            setDefaultPortrait(sex);
        } else {
            try {
                BufferedImage portrait = ImageIO.read(new File(path));
                portraitLabel.setIcon(new ImageIcon(portrait));
            } catch (IOException ex) {
                Logger.getLogger(PersonagePortraitPanel.class.getName()).log(Level.SEVERE, "Cannot find portrait "+path, ex);
                setDefaultPortrait(sex);
            }
        }
    }
    
    private static String getDefaultPortrait(String sex) {
        String path=null;
        
        if ( sex != null && sex.equals("female") ) {
            path = Application.getDataConfiguration().getOption("f_defaultPortrait");
        }
        
        // If still null, that is, no female portrait or option is not set
        if ( path == null) {
            path = Application.getDataConfiguration().getOption("defaultPortrait");
        }
        
        return path;
    }
    
    private void setDefaultPortrait(String sex) {
        String path = getDefaultPortrait(sex);

        try {
            BufferedImage portrait = ImageIO.read(new File(path));
            portraitLabel.setIcon(new ImageIcon(portrait));
            
        } catch (IOException ex) {
            Logger.getLogger(getClass().getName()).log(Level.SEVERE, "Cannot find default portrait "+path, ex);
        }
        
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portraitLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        portraitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/asqueados/vpm/view/swing/noPortrait.png"))); // NOI18N
        portraitLabel.setPreferredSize(new java.awt.Dimension(250, 250));
        add(portraitLabel, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel portraitLabel;
    // End of variables declaration//GEN-END:variables
    
}
