/*
 * SimplePersonagePanel.java
 *
 * Created on 12 de noviembre de 2011, 12:59
 */

package com.asqueados.vpm.view.swing;

import com.asqueados.vpm.entities.Personage;

/**
 *
 * @author  Pablo J. Urbano Santos <flamma at member.fsf.org>
 */
public class SimplePersonagePanel extends javax.swing.JPanel {
    private Personage character;
    
    /** Creates new form SimplePersonagePanel */
    public SimplePersonagePanel() {
        character = null;
        initComponents();
    }
    
    public SimplePersonagePanel(Personage character) {
        this.character = character;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        portraitPanel = new com.asqueados.vpm.view.swing.PersonagePortraitPanel(character);
        personageAttributesPanel1 = new com.asqueados.vpm.view.swing.PersonageAttributesPanel(character);

        setLayout(new java.awt.BorderLayout());
        add(portraitPanel, java.awt.BorderLayout.WEST);
        add(personageAttributesPanel1, java.awt.BorderLayout.LINE_END);
    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.asqueados.vpm.view.swing.PersonageAttributesPanel personageAttributesPanel1;
    private com.asqueados.vpm.view.swing.PersonagePortraitPanel portraitPanel;
    // End of variables declaration//GEN-END:variables
    
}
